HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -e
zstyle :compinstall filename '/home/fabian/.zshrc'

autoload -Uz compinit promptinit
compinit
promptinit

prompt adam1 red

export LANG=sv_SE.UTF-8
export LC_ALL=sv_SE.UTF-8
export LC_CTYPE=sv_SE.UTF-8
export MM_CHARSET=utf8
export PAGER=less

export PATH="$HOME/bin:${PATH}"
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
export PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
export PATH="/Applications/MacVim.app/Contents/Resources/vim/runtime/macros:${PATH}"

export CLICOLOR=exfxcxdxbxegedabagacad
export LSCOLORS=hefxcxdxbxegedabagacad

alias tmux="tmux -2"
alias tm="tmux attach"
alias ap='ssh fabian@apple.tallr.se'

case `uname` in
	Linux)
		alias ls='ls --color=auto'
	;;
esac

setopt histignorespace
